openapi: 3.1.0
info:
  title: vse-go-newsletter-api
  description: Newsletter service allowing to send posts to subscribers.
  version: 0.0.0
servers:
  - url: http://localhost
    description: Localhost server running on HTTP.

paths:
  "/ping":
    get:
      description: Health check
      operationId: Ping
      summary: Check the healthiness of the service
      responses:
        "204":
          description: It's ALIVE (a.k.a. service is up and running)
        "400":
          description: Invalid request
  "/newsletters": {
    # TODO;
  }
components: {}
