ALTER TABLE newsletters
DROP CONSTRAINT fk_owner;

ALTER TABLE newsletters
DROP COLUMN IF EXISTS owner_id;

ALTER TABLE profiles
DROP COLUMN IF EXISTS email;

ALTER TABLE posts
DROP CONSTRAINT fk_newsletter;

DROP TABLE IF EXISTS posts;
